services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fdms_backend
    restart: unless-stopped
    environment:
      - USER_ID
      - GROUP_ID
      - BACKEND_PORT
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    command: ["npm", "run", "dev"]
    networks:
      - fdms
  mobileview:
    build:
      context: ./mobileview
      dockerfile: Dockerfile
    container_name: fdms_mobileview
    restart: unless-stopped
    environment:
      - USER_ID
      - GROUP_ID
      - BACKEND_PORT
    ports:
      - "8100:8100"
    volumes:
      - ./mobileview/app:/app
    command: ["ionic", "serve", "--external", "--no-open", "--configuration=vi"]
    networks:
      - fdms
  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    container_name: fdms_postgres
    restart: unless-stopped
    expose:
      - "5432"
    volumes:
      - ./volumes/postgres_data:/var/lib/postgresql/data
    environment:
      - USER_ID
      - GROUP_ID
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 15s
    networks:
      - fdms
  garage:
    image: dxflrs/garage:v2.0.0
    container_name: fdms_garage
    restart: unless-stopped
    expose:
      - "3900"
      - "3901"
      - "3902"
      - "3903"
      - "3904"
    ports:
      - "3900:3900"
      - "3901:3901"
      - "3902:3902"
      - "3903:3903"
      - "3904:3904"
    volumes:
      - ./garage/garage.toml:/etc/garage/garage.toml
      - ./volumes/garage_meta:/var/lib/garage/meta
      - ./volumes/garage_data:/var/lib/garage/data
    networks:
      - fdms
    user: "${UID}:${GID}"
    environment:
      RUST_LOG: "garage=debug"
    command: ["/garage", "-c", "/etc/garage/garage.toml", "server"]


networks:
  fdms:
    driver: bridge