metadata_dir = "/tmp/meta"
data_dir = "/tmp/data"
db_engine = "sqlite"

replication_factor = 1

rpc_bind_addr = "[::]:3901"
rpc_public_addr = "127.0.0.1:3901"
rpc_secret = "a97541b226e16705ccc6a29c852a5afd00549cc2e05ae63d8aa9b8215fac4dbe"

[s3_api]
s3_region = "garage"
api_bind_addr = "[::]:3900"
root_domain = ".s3.garage.localhost"

[s3_web]
bind_addr = "[::]:3902"
root_domain = ".web.garage.localhost"
index = "index.html"

[k2v_api]
api_bind_addr = "[::]:3904"

[admin]
api_bind_addr = "[::]:3903"
admin_token = "JX4OMbc4fjbAkBR/tcxSKIi0zA9hutrlJsLlWtut3Uk="
metrics_token = "DNZ/ze4W85qwzmhjebZ3BAVZIhdDZbqimn4NZPMi8eY="
