metadata_dir = "/var/lib/garage/meta"
data_dir = "/var/lib/garage/data"
db_engine = "sqlite"

replication_factor = 1

rpc_bind_addr = "[::]:3901"
rpc_public_addr = "[::]:3901"
rpc_secret = "e551e41818e394402d5ecad7540fe45685bf863a38e3862faf99cdb5e2d9f288"

[s3_api]
s3_region = "garage"
api_bind_addr = "[::]:3900"
root_domain = ".s3.garage.localhost"

[s3_web]
bind_addr = "[::]:3902"
root_domain = ".web.garage.localhost"
index = "index.html"

[k2v_api]
api_bind_addr = "[::]:3904"

[admin]
api_bind_addr = "[::]:3903"
admin_token = "Xq5X5etINGsiDy7dQxdfIkjeymhPoH8Xd4udjMJ1Y8M="
metrics_token = "ryL5rbP+BlZ9wyFft8ZbzUXkmuhVQCvFJ+dq8yRPHO0="